### PR TITLE
temporary files do not leak

### PR DESCRIPTION
**Pull request by alexandrupaler**
Applies the patch from #289 
Solves #132 #174
Thank you @kkissell

### CODE REVIEW

**Comment by alexandrupaler** [comment]
@95-martin-orion Is CI disabled on the PRs?

**Comment by 95-martin-orion** [comment]
> @95-martin-orion Is CI disabled on the PRs?

It shouldn't be...I wonder why this didn't run them? Just to be safe, I'll change my review status to "Request changes" until this is sorted out.

**Comment by 95-martin-orion** [comment]
@alexandrupaler, it looks like the Travis check [failed](https://travis-ci.org/github/ngnrsaa/qflex/builds/674181112) but for some reason did not report this to the PR. I'll open a separate issue for preventing this kind of test-silence in the future.

For now, I'd recommend fixing the issues logged in the above link (looks like a build failure in Docker run and a separate YAPF complaint) and checking the [Travis build list](https://travis-ci.org/github/ngnrsaa/qflex/builds) if it still doesn't show up on the PR.

**Comment by alexandrupaler** [comment]
It was a formatting issue. Solved it and Travis does not complain https://travis-ci.org/github/ngnrsaa/qflex/builds/674505974

**Comment by alexandrupaler** [comment]
However, irrespective of this PR, we will need to update tests because Cirq 0.8 will obsolete some calls.

**Comment by alexandrupaler** [comment]
Should I merge this pull request?

**Comment by 95-martin-orion** [comment]
> Should I merge this pull request?

I'd double-check the Travis run first, but if it's passing it's fine to merge.

**Pull request merged**
